##################################
# ServerUtils - A plugin by psgs #
##################################

hubWorld: "hub"

gameLobbyWorld: "hub"

vampireWorld: "vampire"


# HG Arenas:

sg1World: "SG1"
sg2World: "SG2"